### ISSUE TITLE
Filter out full events

### ISSUE THREAD

**Issue by ashbc** [ashbc/tgrsite#29]

**Comment by finnbar** [comment]
I assume this will be done via a link like "Show only RPGs" on the main events page. What should the default be though? I think it should default to hiding full games and then having a url to show them to reduce clutter, however it could be argued the other way - for example, hide by default leads to confusion when someone is told about an event that they can no longer go to because it's full (where's the event gone?) and it might be nice to see full events so people can request them being expanded (e.g. for a draft when interest has been massively underestimated).

**Comment by ashbc** [comment]
> I assume this will be done via a link 

That's a good way of doing it I think - or a checkbox (fancy!)

> I think it should default to hiding full games

Interesting issue, will discuss with the exec - I _think_ I agree?

> nice to see full events so people can request them being expanded 

That gives me a thought - initially hide descriptions of full games (ie collapse them)?
